repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key        # check private keys and tokens
      - id: check-yaml                # check yaml correctness
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: trailing-whitespace
      - id: end-of-file-fixer
